# config.py
# @author: Memba Co.

# === UYGULAMA VERSİYONU ===
APP_VERSION = "1.5.0"

# === YAPAY ZEKA MODEL AYARI ===
GEMINI_MODEL = 'gemini-2.0-flash'

# === ÇOKLU ZAMAN ARALIĞI (MTA) ANALİZİ AYARLARI (MANUEL) ===
USE_MTA_ANALYSIS = True
MTA_TREND_TIMEFRAME = "4h"

# === CANLI İŞLEM AYARI (DİKKAT!) ===
LIVE_TRADING = True

# === EMİR TÜRÜ VE STRATEJİSİ AYARLARI ===
DEFAULT_ORDER_TYPE = 'LIMIT'
USE_AI_LIMIT_PRICE = True

# === TEMEL AYARLAR ===
DEFAULT_MARKET_TYPE = 'future'

# === KALDIRAÇ AYARLARI ===
LEVERAGE = 10.0

# === RİSK YÖNETİMİ AYARLARI ===
RISK_PER_TRADE_PERCENT = 2.0
USE_ATR_FOR_SLTP = True
ATR_MULTIPLIER_SL = 2.0
RISK_REWARD_RATIO_TP = 1.5
USE_TRAILING_STOP_LOSS = True
TRAILING_STOP_ACTIVATION_PERCENT = 1.5

# === POZİSYON YÖNETİMİ AYARLARI ===
MAX_CONCURRENT_TRADES = 3
DATABASE_FILE = "trades.db"
POSITION_CHECK_INTERVAL_SECONDS = 120

# === TELEGRAM BİLDİRİM AYARLARI ===
TELEGRAM_ENABLED = True

# === PROAKTİF TARAMA AYARLARI (GELİŞTİRİLDİ) ===
PROACTIVE_SCAN_ENABLED = True
PROACTIVE_SCAN_INTERVAL_SECONDS = 900
PROACTIVE_SCAN_AUTO_CONFIRM = False
PROACTIVE_SCAN_IN_LOOP = False

# --- Filtreleme ve Liste Yönetimi ---
PROACTIVE_SCAN_USE_GAINERS_LOSERS = True
PROACTIVE_SCAN_TOP_N = 5
PROACTIVE_SCAN_MIN_VOLUME_USDT = 1000000 # (Yeni) Sadece 24s hacmi bu değerin üzerindekileri tara
PROACTIVE_SCAN_BLACKLIST = ["SHIB", "PEPE", "MEME"] # (Yeni) Bu koinleri asla tarama
PROACTIVE_SCAN_WHITELIST = ["BTC", "ETH", "SOL"] # (Yeni) Yükselenler listesinde olmasa bile bunları her zaman tara

# --- Analiz Zekası ---
PROACTIVE_SCAN_MTA_ENABLED = True # (Yeni) Tarama yaparken MTA analizi kullan
PROACTIVE_SCAN_ENTRY_TIMEFRAME = "15m" # (Yeni) Tarama için giriş sinyali zaman aralığı
PROACTIVE_SCAN_TREND_TIMEFRAME = "4h" # (Yeni) Tarama için ana trend zaman aralığı
